ACCEL_ASCII "C:\ram\controller\asap\asap-gain.sch"

(asciiHeader 
  (asciiVersion 3 0)
  (timeStamp 2006 2 20 14 43 17)
  (program "P-CAD 2000 Schematic" "15.10.24")
  (copyright "Copyright © 1992-2000 ACCEL Technologies, Inc.")
  (fileAuthor "ram")
  (headerString "")
  (fileUnits Mil)
  (guidString "{D9087018-1AE5-4663-B36D-A36B2D7E6936}")
)

(library "Library_1"
  (textStyleDef "(Default)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 137.0)
      (strokeWidth 14.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 70.0)
      (strokeWidth 0.11112 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 125.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H120W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 120.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H180W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 180.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H200W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 200.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(DefaultTTF) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 111.2)
      (strokeWidth 0.17653 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H90W15"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 90.0)
      (strokeWidth 15.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (symbolDef "CAP_NP_1"
    (originalName "CAP_NP")
    (pin (pinNum 2) (pt 300.0 0.0) (rotation 180.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 235.0 0.0) "2" (textStyleRef "(PinStyle)") (isFlipped True) (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 320.0 0.0) "B" (textStyleRef "(PinStyle)") (isFlipped True) (justify Right) (extent 2.03437 mm 3.04561 mm) )
      ) 
      (defaultPinDes "2")
    )
    (pin (pinNum 1) (pt 400.0 0.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 465.0 0.0) "1" (textStyleRef "(PinStyle)") (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 380.0 0.0) "A" (textStyleRef "(PinStyle)") (justify Right) (extent 1.81768 mm 3.04561 mm) )
      ) 
      (defaultPinDes "1")
    )
    (line (pt 337.0 -75.0) (pt 337.0 75.0) )
    (line (pt 362.0 0.0) (pt 400.0 0.0) )
    (line (pt 300.0 0.0) (pt 337.0 0.0) )
    (line (pt 362.0 -75.0) (pt 362.0 75.0) )
    (attr "RefDes" "" (pt 350.0 96.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    (attr "Value" "" (pt 350.0 -104.0) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    (attr "Type" "" (pt 350.0 246.0) (justify LowerCenter) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "AGND_SYM_1"
    (originalName "AGND_SYM")
    (pin (pinNum 1) (pt 0.0 -100.0) (rotation 90.0) (pinLength 100.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.0 -35.0) "1" (textStyleRef "(PinStyle)") (rotation 90.0) (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 0.0 -120.0) "GNDA" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 6.44048 mm 3.04561 mm) )
      ) 
    )
    (poly 
      (pt 75.0 -100.0) 
      (pt -75.0 -100.0) 
      (pt 0.0 -200.0) 
    )
    (attr "RefDes" "" (textStyleRef "T:H90W15") )
    (attr "Value" "" (pt 150.0 -200.0) (textStyleRef "(Default)") )
    (attr "Type" "" (textStyleRef "(DefaultTTF)") )
  )
  (symbolDef "DISCRETE_224_N_1"
    (originalName "DISCRETE_224_N")
    (pin (pinNum 1) (pt 300.0 0.0) (rotation 180.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 235.0 0.0) "A" (textStyleRef "(PinStyle)") (isFlipped True) (extent 1.81768 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 320.0 0.0) "A" (textStyleRef "(PinStyle)") (isFlipped True) (justify Right) (extent 1.81768 mm 3.04561 mm) )
      ) 
    )
    (pin (pinNum 2) (pt 600.0 0.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 665.0 0.0) "B" (textStyleRef "(PinStyle)") (extent 2.03437 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 580.0 0.0) "B" (textStyleRef "(PinStyle)") (justify Right) (extent 2.03437 mm 3.04561 mm) )
      ) 
    )
    (line (pt 300.0 0.0) (pt 325.0 50.0) )
    (line (pt 325.0 50.0) (pt 375.0 -50.0) )
    (line (pt 375.0 -50.0) (pt 425.0 50.0) )
    (line (pt 425.0 50.0) (pt 475.0 -50.0) )
    (line (pt 475.0 -50.0) (pt 525.0 50.0) )
    (line (pt 525.0 50.0) (pt 575.0 -50.0) )
    (line (pt 575.0 -50.0) (pt 600.0 0.0) )
    (attr "Type" "" (pt 450.0 221.0) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    (attr "Value" "" (pt 450.0 -79.0) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    (attr "RefDes" "" (pt 450.0 71.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "PSD_CHAN_1"
    (originalName "PSD_CHAN")
    (pin (pinNum 1) (pt 100.0 100.0) (rotation 180.0) (pinLength 100.0) 
      (pinDisplay (dispPinName True) ) 
      (pinDes (text (pt 35.0 100.0) "1" (textStyleRef "(PinStyle)") (isFlipped True) (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 120.0 100.0) "IN1" (textStyleRef "(PinStyle)") (isFlipped True) (justify Right) (extent 4.12908 mm 3.04561 mm) )
      ) 
    )
    (pin (pinNum 2) (pt 1100.0 100.0) (pinLength 100.0) 
      (pinDisplay (dispPinName True) ) 
      (pinDes (text (pt 1165.0 100.0) "2" (textStyleRef "(PinStyle)") (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 1080.0 100.0) "OUT2" (textStyleRef "(PinStyle)") (justify Right) (extent 6.29602 mm 3.04561 mm) )
      ) 
    )
    (line (pt 100.0 0.0) (pt 1100.0 0.0) )
    (line (pt 100.0 0.0) (pt 100.0 200.0) )
    (line (pt 100.0 200.0) (pt 1100.0 200.0) )
    (line (pt 1100.0 0.0) (pt 1100.0 200.0) )
    (line (pt 60.0 -40.0) (pt 1140.0 -40.0) )
    (line (pt 60.0 -40.0) (pt 60.0 240.0) )
    (line (pt 60.0 240.0) (pt 1140.0 240.0) )
    (line (pt 1140.0 -40.0) (pt 1140.0 240.0) )
    (attr "Type" "" (textStyleRef "(PartStyle)") )
    (attr "RefDes" "" (pt 15.23999 mm 9.75704 mm) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    (attr "Value" "" (textStyleRef "(PartStyle)") )
    (attr "Link" "PSD_CHAN" (pt 15.23999 mm -49.5) (isVisible True) (justify UpperCenter) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (symbolDef "CHAN_DUMMY_1"
    (originalName "CHAN_DUMMY")
    (pin (pinNum 1) (pt 100.0 0.0) (rotation 180.0) (pinLength 100.0) 
      (pinDisplay (dispPinName True) ) 
      (pinDes (text (pt 35.0 0.0) "1" (textStyleRef "(PinStyle)") (isFlipped True) (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 120.0 0.0) "" (textStyleRef "(PinStyle)") (isFlipped True) (justify Right) (extent 0.51752 mm 0.51752 mm) )
      ) 
    )
    (pin (pinNum 2) (pt 1100.0 0.0) (pinLength 100.0) 
      (pinDisplay (dispPinName True) ) 
      (pinDes (text (pt 1165.0 0.0) "2" (textStyleRef "(PinStyle)") (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 1080.0 0.0) "" (textStyleRef "(PinStyle)") (justify Right) (extent 0.51752 mm 0.51752 mm) )
      ) 
    )
    (line (pt 1100.0 200.0) (pt 1100.0 -200.0) )
    (line (pt 1100.0 -200.0) (pt 100.0 -200.0) )
    (line (pt 100.0 -200.0) (pt 100.0 200.0) )
    (line (pt 100.0 200.0) (pt 1100.0 200.0) )
    (attr "RefDes" "" (pt 600.0 300.0) (isVisible True) (justify LowerCenter) (textStyleRef "(Default)") )
    (attr "Type" "" (pt 600.0 -300.0) (isVisible True) (justify UpperCenter) (textStyleRef "(Default)") )
  )
  (symbolDef "LINK_PIN_1"
    (originalName "LINK_PIN")
    (pin (pinNum 1) (pt 0.0 0.0) (pinLength 200.0) 
      (pinDisplay (dispPinDes False) (dispPinName True) ) 
      (pinDes (text (pt 65.0 0.0) "1" (textStyleRef "(PinStyle)") (extent 1.96214 mm 3.04561 mm) )
      ) 
      (pinName (text (pt -20.0 0.0) "IN1" (textStyleRef "(PinStyle)") (justify Right) (extent 4.12908 mm 3.04561 mm) )
      ) 
    )
    (line (pt 0.0 0.0) (pt -1.46651 mm 2.54007 mm) )
    (line (pt 0.0 0.0) (pt -1.46651 mm -2.54007 mm) )
    (line (pt 40.0 0.0) (pt -0.45051 mm 2.54007 mm) )
    (line (pt 40.0 0.0) (pt -0.45051 mm -2.54007 mm) )
    (attr "Type" "" (pt 2.25124 mm -0.79057 mm) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    (attr "RefDes" "" (pt 2.25124 mm 9.14017 mm) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    (attr "Value" "" (textStyleRef "(PartStyle)") )
  )
  (symbolDef "DISCRETE_64_N_1"
    (originalName "DISCRETE_64_N")
    (pin (pinNum 1) (pt 0.0 250.0) (rotation 270.0) (pinLength 250.0) 
      (pinDisplay (dispPinDes False) ) 
      (pinDes (text (pt 0.0 185.0) "TP" (textStyleRef "(PinStyle)") (rotation 270.0) (isFlipped True) (extent 3.19007 mm 3.04561 mm) )
      ) 
      (pinName (text (pt 0.0 270.0) "" (textStyleRef "(PinStyle)") (rotation 270.0) (isFlipped True) (justify Right) (extent 0.51752 mm 0.51752 mm) )
      ) 
    )
    (arc (pt 0.0 275.0) (radius 25.0) (startAngle 0.0) (sweepAngle 360.0) (width 10.0) )
    (attr "Type" "" (pt -125.0 446.0) (textStyleRef "(PartStyle)") )
    (attr "RefDes" "" (pt 0.0 321.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    (attr "Value" "" (isVisible True) (textStyleRef "(DefaultTTF)") )
  )
  (symbolDef "OPAMP_1"
    (originalName "OPAMP")
    (pin (pinNum 1) (pt 0.0 -300.0) (rotation 180.0) (pinLength 200.0) 
      (pinDes (text (pt -100.0 -320.0) "3" (textStyleRef "(DefaultTTF) [1]") (rotation 180.0) (justify UpperCenter) (extent 1.79959 mm 3.35407 mm) )
      ) 
      (pinName (text (pt 0.0 -300.0) "IN+" (textStyleRef "(DefaultTTF) [1]") (rotation 180.0) (justify Right) (extent 4.55126 mm 3.35407 mm) )
      ) 
      (defaultPinDes "1")
    )
    (pin (pinNum 2) (pt 0.0 -100.0) (rotation 180.0) (pinLength 200.0) 
      (pinDes (text (pt -100.0 -120.0) "2" (textStyleRef "(DefaultTTF) [1]") (rotation 180.0) (justify UpperCenter) (extent 1.79959 mm 3.35407 mm) )
      ) 
      (pinName (text (pt 0.0 -100.0) "IN-" (textStyleRef "(DefaultTTF) [1]") (rotation 180.0) (justify Right) (extent 4.12792 mm 3.35407 mm) )
      ) 
      (defaultPinDes "2")
    )
    (pin (pinNum 3) (pt 400.0 -200.0) (pinLength 200.0) 
      (pinDes (text (pt 500.0 -220.0) "1" (textStyleRef "(DefaultTTF) [1]") (justify LowerCenter) (extent 1.79959 mm 3.35407 mm) )
      ) 
      (pinName (text (pt 400.0 -200.0) "OUT" (textStyleRef "(DefaultTTF) [1]") (justify Right) (extent 5.60959 mm 3.35407 mm) )
      ) 
      (defaultPinDes "3")
    )
    (line (pt 0.0 0.0) (pt 400.0 -200.0) )
    (line (pt 0.0 -400.0) (pt 400.0 -200.0) )
    (line (pt 0.0 0.0) (pt 0.0 -400.0) )
    (line (pt 40.0 -100.0) (pt 100.0 -100.0) )
    (line (pt 40.0 -300.0) (pt 100.0 -300.0) )
    (line (pt 70.0 -270.0) (pt 70.0 -330.0) )
    (attr "RefDes" "" (pt 300.0 -700.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    (attr "Type" "" (pt 163.0 -817.0) (isVisible True) (justify Left) (textStyleRef "(PartStyle)") )
  )
  (compDef "CAP200_1"
    (originalName "CAP200")
    (compHeader 
      (sourceLibrary "MY.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "C")
      (numType Numeric)
    )
    (compPin "1" (pinName "A") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 1) (pinType Passive) )
    (compPin "2" (pinName "B") (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 1) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "CAP_NP") )
    (attachedPattern (patternNum 1) (patternName "CAP200")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
      )
    )
  )
  (compDef "PSD_CHANL_1"
    (originalName "PSD_CHANL")
    (compHeader 
      (sourceLibrary "")
      (compType Link)
      (numPins 2)
      (numParts 2)
      (composition Heterogeneous)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "L")
      (numType Numeric)
    )
    (compPin "1" (pinName "IN1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Input) )
    (compPin "2" (pinName "OUT2") (partNum 2) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Output) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "LINK_PIN") )
    (attachedSymbol (partNum 2) (altType Normal) (symbolName "LINK_PIN") )
  )
  (compDef "OPA2336E_1"
    (originalName "OPA2336E")
    (compHeader 
      (sourceLibrary "MY.LIB")
      (numPins 8)
      (numParts 2)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "U")
    )
    (compPin "1" (pinName "OUT") (partNum 1) (symPinNum 3) (gateEq 1) (pinEq 0) (pinType Output) )
    (compPin "2" (pinName "IN-") (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 0) (pinType Input) )
    (compPin "3" (pinName "IN+") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Input) )
    (compPin "4" (pinName "V-") (partNum 0) (symPinNum 0) (gateEq 0) (pinEq 0) (pinType Power) )
    (compPin "5" (pinName "IN+") (partNum 2) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Input) )
    (compPin "6" (pinName "IN-") (partNum 2) (symPinNum 2) (gateEq 1) (pinEq 0) (pinType Input) )
    (compPin "7" (pinName "OUT") (partNum 2) (symPinNum 3) (gateEq 1) (pinEq 0) (pinType Output) )
    (compPin "8" (pinName "V+") (partNum 0) (symPinNum 0) (gateEq 0) (pinEq 0) (pinType Power) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "OPAMP") )
    (attachedSymbol (partNum 2) (altType Normal) (symbolName "OPAMP") )
    (attachedPattern (patternNum 1) (patternName "ALT_MSOP8")
      (numPads 8)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
        (padNum  3) (compPinRef "3")
        (padNum  4) (compPinRef "4")
        (padNum  5) (compPinRef "5")
        (padNum  6) (compPinRef "6")
        (padNum  7) (compPinRef "7")
        (padNum  8) (compPinRef "8")
      )
    )
  )
  (compDef "PSD_CHAN_DUM_1"
    (originalName "PSD_CHAN_DUM")
    (compHeader 
      (sourceLibrary "ASAP.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "M")
    )
    (compPin "1" (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Input) )
    (compPin "2" (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 0) (pinType Output) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "CHAN_DUMMY") )
    (attachedPattern (patternNum 1) (patternName "CHAN_DUM_PAT")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
      )
    )
  )
  (compDef "GNDANALOG_1"
    (originalName "GNDANALOG")
    (compHeader 
      (sourceLibrary "MY.LIB")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "PWR")
    )
    (compPin "1" (pinName "GNDA") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "AGND_SYM") )
  )
  (compDef "RES400_1"
    (originalName "RES400")
    (compHeader 
      (sourceLibrary "DISCRETE.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "R")
      (numType Numeric)
    )
    (compPin "A" (pinName "A") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 1) (pinType Passive) )
    (compPin "B" (pinName "B") (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 1) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "DISCRETE_224_N") )
    (attachedPattern (patternNum 1) (patternName "RES400")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "A")
        (padNum  2) (compPinRef "B")
      )
    )
  )
  (compDef "PSD_CHAN_1"
    (originalName "PSD_CHAN")
    (compHeader 
      (sourceLibrary "")
      (compType Module)
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "M")
    )
    (compPin "1" (pinName "IN1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Input) )
    (compPin "2" (pinName "OUT2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Output) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "PSD_CHAN") )
  )
  (compDef "TESTPOINT1MM_1"
    (originalName "TESTPOINT1MM")
    (compHeader 
      (sourceLibrary "MY.LIB")
      (numPins 1)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "TP")
      (numType Numeric)
    )
    (compPin "TP" (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "DISCRETE_64_N") )
    (attachedPattern (patternNum 1) (patternName "TESTPOINT1MM")
      (numPads 1)
      (padPinMap 
        (padNum  1) (compPinRef "TP")
      )
    )
  )
  (compDef "CAP200BOX_1"
    (originalName "CAP200BOX")
    (compHeader 
      (sourceLibrary "MY.LIB")
      (numPins 2)
      (numParts 1)
      (alts (ieeeAlt False) (deMorganAlt False))
      (refDesPrefix "C")
      (numType Numeric)
    )
    (compPin "1" (pinName "A") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 1) (pinType Passive) )
    (compPin "2" (pinName "B") (partNum 1) (symPinNum 2) (gateEq 1) (pinEq 1) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "CAP_NP") )
    (attachedPattern (patternNum 1) (patternName "CAP200BOX")
      (numPads 2)
      (padPinMap 
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
      )
    )
  )
)

(netlist "Netlist_1"
  (compInst "M2"
    (compRef "PSD_CHAN_1")
    (originalName "PSD_CHAN")
    (attr "Link" "PSD_CHAN" (isVisible True) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "U1"
    (compRef "OPA2336E_1")
    (originalName "OPA2336E")
    (patternName "ALT_MSOP8")
  )
  (compInst "PSD_CHAN"
    (compRef "PSD_CHANL_1")
    (originalName "PSD_CHANL")
  )
  (compInst "M1"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "C1"
    (compRef "CAP200_1")
    (originalName "CAP200")
    (compValue "5.6nF")
    (patternName "CAP200")
    (attr "Description" "Capacitor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "C3"
    (compRef "CAP200_1")
    (originalName "CAP200")
    (compValue "2.7nF")
    (patternName "CAP200")
    (attr "Description" "Capacitor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "R2"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "8.45K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "R3"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "12.4K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "M3"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "R5"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "16K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "M4"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "M5"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "R6"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "1K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "R4"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "9K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "PWR1"
    (compRef "GNDANALOG_1")
    (originalName "GNDANALOG")
    (attr "Description" "Analog Ground" (pt 1.0 -3.0) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "M6"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "PWR3"
    (compRef "GNDANALOG_1")
    (originalName "GNDANALOG")
    (attr "Description" "Analog Ground" (pt 1.0 -3.0) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "TP2"
    (compRef "TESTPOINT1MM_1")
    (originalName "TESTPOINT1MM")
    (compValue "YIN")
    (patternName "TESTPOINT1MM")
    (attr "Description" "Test Point" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "PSD_CHAN1"
    (compRef "PSD_CHANL_1")
    (originalName "PSD_CHANL")
  )
  (compInst "C2"
    (compRef "CAP200BOX_1")
    (originalName "CAP200BOX")
    (compValue "100nF")
    (patternName "CAP200BOX")
    (attr "Description" "Capacitor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "PWR2"
    (compRef "GNDANALOG_1")
    (originalName "GNDANALOG")
    (attr "Description" "Analog Ground" (pt 1.0 -3.0) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "R1"
    (compRef "RES400_1")
    (originalName "RES400")
    (compValue "1K")
    (patternName "RES400")
    (attr "Description" "Resistor" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "TP1"
    (compRef "TESTPOINT1MM_1")
    (originalName "TESTPOINT1MM")
    (compValue "YIN")
    (patternName "TESTPOINT1MM")
    (attr "Description" "Test Point" (pt 412.0 483.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
  )
  (compInst "M7"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (compInst "M8"
    (compRef "PSD_CHAN_DUM_1")
    (originalName "PSD_CHAN_DUM")
    (patternName "CHAN_DUM_PAT")
  )
  (net "V+"
    (node "U1" "8")
  )
  (net "GNDA"
    (node "C3" "2")
    (node "PWR1" "1")
    (node "R6" "A")
    (node "PWR3" "1")
    (node "PWR2" "1")
    (node "R5" "A")
  )
  (net "NET00000"
    (node "R2" "A")
    (node "U1" "7")
    (node "R4" "B")
  )
  (net "NET00001"
    (node "U1" "6")
    (node "R6" "B")
    (node "R4" "A")
  )
  (net "NET00018"
    (node "R2" "B")
    (node "R3" "A")
    (node "C1" "2")
  )
  (net "NET00034"
    (node "C3" "1")
    (node "R3" "B")
    (node "U1" "3")
  )
  (net "NET00007"
    (node "PSD_CHAN" "2")
    (node "TP2" "TP")
    (node "C1" "1")
    (node "U1" "2")
    (node "U1" "1")
  )
  (net "NET00002"
    (node "R1" "B")
    (node "U1" "5")
  )
  (net "NET00003"
    (node "R1" "A")
    (node "R5" "B")
    (node "C2" "1")
  )
  (net "NET00004"
    (node "PSD_CHAN1" "1")
    (node "TP1" "TP")
    (node "C2" "2")
  )
  (net "V-"
    (node "U1" "4")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader 
    (workspaceSize 11000.0 8500.0)
    (gridDfns 
      (grid "50.0mil")
      (grid "1.0mil")
      (grid "100.0mil")
    )
    (designInfo 
      (fieldSet "(Default)"
        (fieldDef "Date" "")
        (fieldDef "Time" "")
        (fieldDef "Author" "ram")
        (fieldDef "Revision" "A")
        (fieldDef "Title" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
      )
    )
  )
  (titleSheet 
     "C:\\Program Files\\P-CAD 2000\\Titles\\A.ttl"
    1.0000 
    (isVisible True)
    (offset 0.0 0.0)
    (border
      (isVisible False)
      (height 7500.0)
      (width 10000.0)
      (offset 500.0 500.0)
    )
    (zones
      (isVisible False) 
      (textStyleRef "(Default)") 
      (horizontalZones 1
        (numDirection ascending)
        (numType Alphabetic)
      )
      (verticalZones 1 
        (numDirection ascending)
        (numType Numeric)
      ) 
    ) 
    (line (pt 1095.0 717.5) (pt 1095.0 7417.5) )(line (pt 1095.0 7417.5) (pt 10295.0 7417.5) )(line (pt 8095.0 7417.5) (pt 8095.0 7617.5) )(line (pt 5695.0 7417.5) (pt 5695.0 7617.5) )(line (pt 3295.0 7417.5) (pt 3295.0 7617.5) )(line (pt 895.0 5817.5) (pt 1095.0 5817.5) )(line (pt 895.0 2317.5) (pt 1095.0 2317.5) )(line (pt 895.0 517.5) (pt 895.0 7617.5) )(line (pt 895.0 7617.5) (pt 10495.0 7617.5) )(line (pt 10295.0 5817.5) (pt 10495.0 5817.5) )(line (pt 8095.0 517.5) (pt 8095.0 717.5) )(line (pt 5695.0 517.5) (pt 5695.0 717.5) )(line (pt 3295.0 517.5) (pt 3295.0 717.5) )(line (pt 1095.0 717.5) (pt 10295.0 717.5) )(line (pt 10295.0 717.5) (pt 10295.0 7417.5) )(line (pt 895.0 517.5) (pt 10495.0 517.5) )(line (pt 10495.0 517.5) (pt 10495.0 7617.5) )(line (pt 7295.0 717.5) (pt 7295.0 1717.5) )(line (pt 7295.0 1717.5) (pt 10295.0 1717.5) )(line (pt 7295.0 1417.5) (pt 10295.0 1417.5) )(line (pt 7295.0 1017.5) (pt 10295.0 1017.5) )(line (pt 7795.0 1017.5) (pt 7795.0 1417.5) )(line (pt 9795.0 1017.5) (pt 9795.0 1417.5) )(line (pt 7295.0 867.5) (pt 10295.0 867.5) )(line (pt 9095.0 717.5) (pt 9095.0 1017.5) )(text (pt 7345.0 1617.5) "Title" (textStyleRef "(Default)") (justify Left) (extent 5.49275 mm 135.0) )
    (text (pt 7345.0 1317.5) "Size" (textStyleRef "(Default)") (justify Left) (extent 5.57212 mm 135.0) )
    (text (pt 7345.0 942.5) "Date" (textStyleRef "(Default)") (justify Left) (extent 6.12775 mm 135.0) )
    (text (pt 7345.0 792.5) "Filename" (textStyleRef "(Default)") (justify Left) (extent 11.52525 mm 135.0) )
    (text (pt 9145.0 942.5) "Drawn by" (textStyleRef "(Default)") (justify Left) (extent 11.84275 mm 135.0) )
    (text (pt 9145.0 792.5) "Sheet" (textStyleRef "(Default)") (justify Left) (extent 7.47712 mm 135.0) )
    (text (pt 9795.0 792.5) "of" (textStyleRef "(Default)") (justify Left) (extent 3.03212 mm 135.0) )
    (text (pt 9845.0 1317.5) "Rev" (textStyleRef "(Default)") (justify Left) (extent 4.93712 mm 135.0) )
    (text (pt 7545.0 1142.5) "A" (textStyleRef "T:H200W10") (justify Center) (extent 147.5 260.0) )
    (text (pt 7845.0 1317.5) "Number" (textStyleRef "(Default)") (justify Left) (extent 10.17587 mm 135.0) )
    (line (pt 10295.0 2317.5) (pt 10495.0 2317.5) )(line (pt 10295.0 4067.5) (pt 10495.0 4067.5) )(line (pt 895.0 4067.5) (pt 1095.0 4067.5) )(text (pt 10395.0 3192.5) "3" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 4942.5) "2" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 6717.5) "1" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 1417.5) "4" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 1417.5) "4" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 3192.5) "3" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 4942.5) "2" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 6717.5) "1" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 2095.0 7517.5) "A" (textStyleRef "T:H180W10") (justify Center) (extent 3.39725 mm 235.0) )
    (text (pt 4520.0 7517.5) "B" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 6895.0 7517.5) "C" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 9295.0 7517.5) "D" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 9295.0 617.5) "D" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 6895.0 617.5) "C" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 4495.0 617.5) "B" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 2095.0 617.5) "A" (textStyleRef "T:H180W10") (justify Center) (extent 3.39725 mm 235.0) )
  )
  (sheet "Sheet1" (sheetNum 1)
    (fieldSetRef "(Default)")
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 0.0 0.0) (pt 0.0 0.0) )
  )
  (sheet "tables" (sheetNum 9)
    (fieldSetRef "(Default)")
    (text (pt 7742.0 1501.0) "Brake controller: power table" (textStyleRef "(DefaultTTF)") (extent 37.00197 mm 3.7703 mm) )
    (field "Author" (pt 9772.0 884.0) (textStyleRef "(DefaultTTF)") )
    (field "Revision" (pt 9948.0 1107.0) (textStyleRef "(DefaultTTF)") )
    (field "Modified Date" (pt 7763.0 882.0) (textStyleRef "(DefaultTTF)") )
    (field "Filename" (pt 7939.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Sheet Number" (pt 9610.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Number Of Sheets" (pt 10053.0 731.0) (textStyleRef "(DefaultTTF)") )
    (table powerTable
      (pt 1300.0 900.0) 
      (extent 2032.5 11.33475 mm) 
      (title "Power Table")
      (textStyleRef "(Default)") 
      (powerTableInfo
        (allPins False)
        (allComponents False)
      )
    )
    (drawBorder True)
    (EntireDesign True)
    (isRotated True)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 1295.0 895.0) (pt 4115.0 2356.3) )
  )
  (sheet "sens_conn" (sheetNum 5)
    (fieldSetRef "(Default)")
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M1") (partNum 1) (pt 4100.0 4900.0) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M3") (partNum 1) (pt 4100.0 3700.0) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M4") (partNum 1) (pt 4100.0 2600.0) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M5") (partNum 1) (pt 4100.0 1600.0) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M6") (partNum 1) (pt 6100.0 2600.0) )
    (symbol (symbolRef "PSD_CHAN_1") (refDesRef "M2") (partNum 1) (pt 4100.0 5700.0) 
      (attr "Link" "PSD_CHAN" (pt 15.23999 mm -49.5) (isVisible True) (justify UpperCenter) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (text (pt 7774.0 1493.0) "ASAP conditioning" (textStyleRef "(DefaultTTF)") (extent 24.30197 mm 3.7703 mm) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M7") (partNum 1) (pt 6400.0 3800.0) )
    (symbol (symbolRef "CHAN_DUMMY_1") (refDesRef "M8") (partNum 1) (pt 6400.0 5000.0) )
    (field "Author" (pt 9788.0 884.0) (textStyleRef "(DefaultTTF)") )
    (field "Revision" (pt 9964.0 1107.0) (textStyleRef "(DefaultTTF)") )
    (field "Modified Date" (pt 7779.0 882.0) (textStyleRef "(DefaultTTF)") )
    (field "Filename" (pt 7955.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Sheet Number" (pt 9626.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Number Of Sheets" (pt 10069.0 731.0) (textStyleRef "(DefaultTTF)") )
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 0.0 0.0) (pt 0.0 0.0) )
  )
  (sheet "PSD_CHAN" (sheetNum 12)
    (fieldSetRef "(Default)")
    (wire (line (pt 5100.0 4600.0) (pt 5300.0 4600.0) (width 10.0) (netNameRef "NET00000") )
    )
    (wire (line (pt 4300.0 4500.0) (pt 4100.0 4500.0) (width 10.0) (netNameRef "NET00001") )
    )
    (wire (line (pt 4200.0 4700.0) (pt 4300.0 4700.0) (width 10.0) (netNameRef "NET00002") )
    )
    (wire (line (pt 3200.0 4700.0) (pt 3300.0 4700.0) (width 10.0) (netNameRef "NET00003") )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R1") (partNum 1) (pt 3300.0 4700.0) 
      (attr "Description" "Resistor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (wire (line (pt 5300.0 4600.0) (pt 5500.0 4600.0) (width 10.0) (netNameRef "NET00000") )
    )
    (wire (line (pt 7700.0 4600.0) (pt 7800.0 4600.0) (width 10.0) (netNameRef "NET00034") )
    )
    (wire (line (pt 7500.0 4600.0) (pt 7700.0 4600.0) (width 10.0) (netNameRef "NET00034") )
    )
    (wire (line (pt 6500.0 4600.0) (pt 6600.0 4600.0) (width 10.0) (netNameRef "NET00018") )
    )
    (symbol (symbolRef "LINK_PIN_1") (refDesRef "PSD_CHAN") (partNum 2) (pt 9300.0 4700.0) (isFlipped True)
      (attr "Type" "" (pt -2.25124 mm -0.79057 mm) (isFlipped True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
      (attr "RefDes" "" (pt -2.25124 mm 9.14017 mm) (isFlipped True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    )
    (wire (line (pt 6400.0 4600.0) (pt 6500.0 4600.0) (width 10.0) (netNameRef "NET00018") )
    )
    (symbol (symbolRef "CAP_NP_1") (refDesRef "C3") (partNum 1) (pt 7700.0 3900.0) (rotation 90.0) 
      (attr "Type" "" (pt -246.0 350.0) (rotation 90.0) (justify LowerCenter) (textStyleRef "(PartStyle)") )
      (attr "Description" "Capacitor" (rotation 90.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
      (attr "RefDes" "" (pt -300.0 400.0) (rotation 180.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
      (attr "Value" "" (pt -300.0 200.0) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
    )
    (symbol (symbolRef "AGND_SYM_1") (refDesRef "PWR1") (partNum 1) (pt 7700.0 3900.0) 
      (attr "Description" "Analog Ground" (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R2") (partNum 1) (pt 5500.0 4600.0) 
      (attr "Description" "Resistor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R3") (partNum 1) (pt 6600.0 4600.0) 
      (attr "Description" "Resistor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "DISCRETE_64_N_1") (refDesRef "TP2") (partNum 1) (pt 8900.0 4700.0) 
      (attr "Description" "Test Point" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (text (pt 6900.0 5800.0) "4 kHz 2 pole butterworth lowpass filter" (textStyleRef "(DefaultTTF)") (extent 48.8553 mm 3.7703 mm) )
    (wire (line (pt 8600.0 4700.0) (pt 8900.0 4700.0) (width 10.0) (netNameRef "NET00007") )
    )
    (wire (line (pt 9100.0 4700.0) (pt 8900.0 4700.0) (width 10.0) (netNameRef "NET00007") )
    )
    (wire (line (pt 6500.0 5200.0) (pt 6500.0 4600.0) (width 10.0) (netNameRef "NET00018") )
    )
    (wire (line (pt 7800.0 5200.0) (pt 7800.0 4800.0) (width 10.0) (netNameRef "NET00007") )
    )
    (wire (line (pt 8600.0 5200.0) (pt 8600.0 4700.0) (width 10.0) (netNameRef "NET00007") )
    )
    (wire (line (pt 6800.0 5200.0) (pt 6500.0 5200.0) (width 10.0) (netNameRef "NET00018") )
    )
    (symbol (symbolRef "CAP_NP_1") (refDesRef "C1") (partNum 1) (pt 6800.0 5200.0) 
      (attr "Description" "Capacitor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (wire (line (pt 8600.0 5200.0) (pt 7800.0 5200.0) (width 10.0) (netNameRef "NET00007") )
    )
    (wire (line (pt 7800.0 5200.0) (pt 7500.0 5200.0) (width 10.0) (netNameRef "NET00007") )
    )
    (symbol (symbolRef "OPAMP_1") (refDesRef "U1") (partNum 2) (pt 4500.0 4400.0) (rotation 180.0) (isFlipped True)
      (attr "Type" "" (pt 300.0 500.0) (rotation 180.0) (isFlipped True) (isVisible True) (justify Left) (textStyleRef "(PartStyle)") )
      (attr "RefDes" "" (pt 475.0 779.0) (rotation 180.0) (isFlipped True) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    )
    (symbol (symbolRef "OPAMP_1") (refDesRef "U1") (partNum 1) (pt 8000.0 4900.0) )
    (wire (line (pt 4100.0 4500.0) (pt 4100.0 4000.0) (width 10.0) (netNameRef "NET00001") )
    )
    (wire (line (pt 3200.0 4000.0) (pt 3200.0 4700.0) (width 10.0) (netNameRef "NET00003") )
    )
    (wire (line (pt 5300.0 4600.0) (pt 5300.0 4000.0) (width 10.0) (netNameRef "NET00000") )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R6") (partNum 1) (pt 4100.0 3100.0) (rotation 90.0) 
      (attr "Description" "Resistor" (rotation 90.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
      (attr "Type" "" (pt -221.0 450.0) (rotation 90.0) (justify LowerCenter) (textStyleRef "(PartStyle)") )
      (attr "Value" "" (pt 79.0 450.0) (rotation 90.0) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
      (attr "RefDes" "" (pt -71.0 450.0) (rotation 90.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R4") (partNum 1) (pt 4400.0 4000.0) 
      (attr "Description" "Resistor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "AGND_SYM_1") (refDesRef "PWR3") (partNum 1) (pt 4100.0 3000.0) 
      (attr "Description" "Analog Ground" (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "AGND_SYM_1") (refDesRef "PWR2") (partNum 1) (pt 3200.0 3000.0) 
      (attr "Description" "Analog Ground" (textStyleRef "(Default)") (constraintUnits string) )
    )
    (wire (line (pt 3200.0 3100.0) (pt 3200.0 3000.0) (width 10.0) (netNameRef "GNDA") )
    )
    (wire (line (pt 4100.0 3100.0) (pt 4100.0 3000.0) (width 10.0) (netNameRef "GNDA") )
    )
    (wire (line (pt 4400.0 4000.0) (pt 4100.0 4000.0) (width 10.0) (netNameRef "NET00001") )
    )
    (wire (line (pt 3100.0 4700.0) (pt 3200.0 4700.0) (width 10.0) (netNameRef "NET00003") )
    )
    (symbol (symbolRef "LINK_PIN_1") (refDesRef "PSD_CHAN1") (partNum 1) (pt 2000.0 4700.0) )
    (wire (line (pt 2400.0 4700.0) (pt 2300.0 4700.0) (width 10.0) (netNameRef "NET00004") )
    )
    (wire (line (pt 2200.0 4700.0) (pt 2300.0 4700.0) (width 10.0) (netNameRef "NET00004") )
    )
    (symbol (symbolRef "DISCRETE_64_N_1") (refDesRef "TP1") (partNum 1) (pt 2300.0 4700.0) 
      (attr "Description" "Test Point" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (symbol (symbolRef "DISCRETE_224_N_1") (refDesRef "R5") (partNum 1) (pt 3200.0 3100.0) (rotation 90.0) 
      (attr "Description" "Resistor" (rotation 90.0) (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
      (attr "Type" "" (pt -221.0 450.0) (rotation 90.0) (justify LowerCenter) (textStyleRef "(PartStyle)") )
      (attr "Value" "" (pt 79.0 450.0) (rotation 90.0) (isVisible True) (justify UpperCenter) (textStyleRef "(PartStyle)") )
      (attr "RefDes" "" (pt -71.0 450.0) (rotation 90.0) (isVisible True) (justify LowerCenter) (textStyleRef "(PartStyle)") )
    )
    (symbol (symbolRef "CAP_NP_1") (refDesRef "C2") (partNum 1) (pt 2400.0 4700.0) 
      (attr "Description" "Capacitor" (justify LowerRight) (textStyleRef "(Default)") (constraintUnits string) )
    )
    (text (pt 4800.0 5800.0) "Gain stage" (textStyleRef "(DefaultTTF)") (extent 14.35363 mm 3.7703 mm) )
    (text (pt 2200.0 5800.0) "AC coupling, 100 Hz high-pass" (textStyleRef "(DefaultTTF)") (extent 39.75363 mm 3.7703 mm) )
    (text (pt 7700.0 1500.0) "ASAP conditioning: one channel (4 per PSD)" (textStyleRef "(DefaultTTF)") (extent 57.32197 mm 3.7703 mm) )
    (text (pt 4600.0 3000.0) "LF412?  LT1355?  OPA2604?" (textStyleRef "(DefaultTTF)") (extent 38.6953 mm 3.7703 mm) )
    (junction (pt 5300.0 4600.0) (netNameRef "NET00000") )
    (junction (pt 4100.0 4000.0) (netNameRef "NET00001") )
    (junction (pt 6500.0 4600.0) (netNameRef "NET00018") )
    (junction (pt 7700.0 4600.0) (netNameRef "NET00034") )
    (junction (pt 8600.0 4700.0) (netNameRef "NET00007") )
    (junction (pt 8900.0 4700.0) (netNameRef "NET00007") )
    (junction (pt 7800.0 5200.0) (netNameRef "NET00007") )
    (junction (pt 3200.0 4700.0) (netNameRef "NET00003") )
    (junction (pt 2300.0 4700.0) (netNameRef "NET00004") )
    (field "Author" (pt 9788.0 884.0) (textStyleRef "(DefaultTTF)") )
    (field "Revision" (pt 9964.0 1107.0) (textStyleRef "(DefaultTTF)") )
    (field "Modified Date" (pt 7779.0 882.0) (textStyleRef "(DefaultTTF)") )
    (field "Filename" (pt 7955.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Sheet Number" (pt 9626.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Number Of Sheets" (pt 10069.0 731.0) (textStyleRef "(DefaultTTF)") )
    (drawBorder True)
    (EntireDesign True)
    (isRotated False)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 0.0 0.0) (pt 0.0 0.0) )
  )
  (schematicPrintSettings 
    (sheetList 
      (sheetRef 1)
      (sheetRef 2)
      (sheetRef 3)
    )
  )

  (programState 
    (layerState 
      (currentLayer (layerNumRef 12))
    )
    (gridState 
      (currentAbsGrid "100.0mil")
      (currentRelGrid "100.0mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording True))
    (currentTextStyle "(DefaultTTF)")
  )

  (reportSettings 
    (reportStyle reportStyleAccel)
    (reportDestination DestinationScreen)
    (pt 0.0 0.0) 
    (reportDefinitions 
      (reportDefinition 
        (reportName "Attributes")
        (reportExtension "atr")
        (reportType ReportTypeAttributes)
        (reportLinesPerPage 70)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "OriginalName")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "Description")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "ComponentField7")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField6")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "Part Number")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
          )
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Bill of Materials")
        (reportExtension "bom")
        (reportShowFlag True)
        (reportType ReportTypeBillOfMaterials)
        (reportLinesPerPage 62)
        (reportColumnWidth 25)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 3)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "_Count")
              (reportFieldType PropertyTypeCount)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "ComponentName")
              (reportFieldType PropertyTypeComponentName)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 13)
            )
            (reportField 
              (reportFieldName "PatternName")
              (reportFieldType PropertyTypePatternName)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "OriginalName")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "Description")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "ComponentField6")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField7")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "SimType")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimModel")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "SimFile")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimPins")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimNetlist")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 10)
            )
            (reportField 
              (reportFieldName "OrigRefDes")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 10)
            )
            (reportField 
              (reportFieldName "Part Number")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Global Nets")
        (reportExtension "gnr")
        (reportType ReportTypeGlobalNets)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Last Used RefDes")
        (reportExtension "lud")
        (reportType ReportTypeLastRefdes)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Library Contents")
        (reportExtension "lct")
        (reportType ReportTypeLibrary)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
      )
      (reportDefinition 
        (reportName "Parts Locations")
        (reportExtension "plc")
        (reportType ReportTypePartsLocations)
        (reportLinesPerPage 62)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "LocationX")
              (reportFieldType PropertyTypeLocationX)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "LocationY")
              (reportFieldType PropertyTypeLocationY)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "Rotation")
              (reportFieldType PropertyTypeRotation)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Parts Usage")
        (reportExtension "ptu")
        (reportType ReportTypePartsUsage)
        (reportLinesPerPage 62)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Unused Parts")
              (reportFieldType PropertyTypeUnusedParts)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "ComponentLibrary")
              (reportFieldType PropertyTypeComponentLibrary)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 16)
            )
          )
        )
      )
    )
  )
)
