cp -p ASAP-RESOLVE.BOT zip/ASAP.BOT
cp -p ASAP-RESOLVE.BSM zip/ASAP.BSM
cp -p ASAP-RESOLVE.DRL zip/ASAP.DRL
cp -p ASAP-RESOLVE.FAB zip/ASAP.FAB
cp -p ASAP-RESOLVE.TOP zip/ASAP.TOP
cp -p ASAP-RESOLVE.TSM zip/ASAP.TSM
cp -p ASAP-RESOLVE.TSS zip/ASAP.TSS
