ACCEL_ASCII "C:\Documents and Settings\ram\My Documents\work\controller\asap_new\probe_breakout.sch"

(asciiHeader 
  (asciiVersion 3 0)
  (timeStamp 2007 10 26 15 25 47)
  (program "P-CAD 2000 Schematic" "15.10.24")
  (copyright "Copyright © 1992-2000 ACCEL Technologies, Inc.")
  (fileAuthor "ram")
  (headerString "")
  (fileUnits Mil)
  (guidString "{61822043-ED70-4BA4-8917-86DBAB620CEC}")
)

(library "Library_1"
  (textStyleDef "(Default)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PartStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 137.0)
      (strokeWidth 14.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(WireStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PortStyle)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "Quality")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 70.0)
      (strokeWidth 0.11112 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Arial")
      (fontHeight 125.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H120W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 120.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H180W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 180.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "T:H200W10"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 200.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(DefaultTTF) [1]"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font 
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 111.2)
      (strokeWidth 0.17653 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "T:H90W15"
    (font 
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 90.0)
      (strokeWidth 15.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
)

(netlist "Netlist_1"
)

(schematicDesign "SchDesign_1"
  (schDesignHeader 
    (workspaceSize 11000.0 8500.0)
    (gridDfns 
      (grid "1.0mil")
      (grid "50.0mil")
      (grid "100.0mil")
    )
    (designInfo 
      (fieldSet "(Default)"
        (fieldDef "Date" "")
        (fieldDef "Time" "")
        (fieldDef "Author" "ram")
        (fieldDef "Revision" "A")
        (fieldDef "Title" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
      )
    )
  )
  (titleSheet 
     "C:\\Program Files\\P-CAD 2000\\Titles\\A.ttl"
    1.0000 
    (isVisible True)
    (offset 0.0 0.0)
    (border
      (isVisible False)
      (height 7500.0)
      (width 10000.0)
      (offset 500.0 500.0)
    )
    (zones
      (isVisible False) 
      (textStyleRef "(Default)") 
      (horizontalZones 1
        (numDirection ascending)
        (numType Alphabetic)
      )
      (verticalZones 1 
        (numDirection ascending)
        (numType Numeric)
      ) 
    ) 
    (line (pt 1095.0 717.5) (pt 1095.0 7417.5) )(line (pt 1095.0 7417.5) (pt 10295.0 7417.5) )(line (pt 8095.0 7417.5) (pt 8095.0 7617.5) )(line (pt 5695.0 7417.5) (pt 5695.0 7617.5) )(line (pt 3295.0 7417.5) (pt 3295.0 7617.5) )(line (pt 895.0 5817.5) (pt 1095.0 5817.5) )(line (pt 895.0 2317.5) (pt 1095.0 2317.5) )(line (pt 895.0 517.5) (pt 895.0 7617.5) )(line (pt 895.0 7617.5) (pt 10495.0 7617.5) )(line (pt 10295.0 5817.5) (pt 10495.0 5817.5) )(line (pt 8095.0 517.5) (pt 8095.0 717.5) )(line (pt 5695.0 517.5) (pt 5695.0 717.5) )(line (pt 3295.0 517.5) (pt 3295.0 717.5) )(line (pt 1095.0 717.5) (pt 10295.0 717.5) )(line (pt 10295.0 717.5) (pt 10295.0 7417.5) )(line (pt 895.0 517.5) (pt 10495.0 517.5) )(line (pt 10495.0 517.5) (pt 10495.0 7617.5) )(line (pt 7295.0 717.5) (pt 7295.0 1717.5) )(line (pt 7295.0 1717.5) (pt 10295.0 1717.5) )(line (pt 7295.0 1417.5) (pt 10295.0 1417.5) )(line (pt 7295.0 1017.5) (pt 10295.0 1017.5) )(line (pt 7795.0 1017.5) (pt 7795.0 1417.5) )(line (pt 9795.0 1017.5) (pt 9795.0 1417.5) )(line (pt 7295.0 867.5) (pt 10295.0 867.5) )(line (pt 9095.0 717.5) (pt 9095.0 1017.5) )(text (pt 7345.0 1617.5) "Title" (textStyleRef "(Default)") (justify Left) (extent 5.49275 mm 135.0) )
    (text (pt 7345.0 1317.5) "Size" (textStyleRef "(Default)") (justify Left) (extent 5.57212 mm 135.0) )
    (text (pt 7345.0 942.5) "Date" (textStyleRef "(Default)") (justify Left) (extent 6.12775 mm 135.0) )
    (text (pt 7345.0 792.5) "Filename" (textStyleRef "(Default)") (justify Left) (extent 11.52525 mm 135.0) )
    (text (pt 9145.0 942.5) "Drawn by" (textStyleRef "(Default)") (justify Left) (extent 11.84275 mm 135.0) )
    (text (pt 9145.0 792.5) "Sheet" (textStyleRef "(Default)") (justify Left) (extent 7.47712 mm 135.0) )
    (text (pt 9795.0 792.5) "of" (textStyleRef "(Default)") (justify Left) (extent 3.03212 mm 135.0) )
    (text (pt 9845.0 1317.5) "Rev" (textStyleRef "(Default)") (justify Left) (extent 4.93712 mm 135.0) )
    (text (pt 7545.0 1142.5) "A" (textStyleRef "T:H200W10") (justify Center) (extent 147.5 260.0) )
    (text (pt 7845.0 1317.5) "Number" (textStyleRef "(Default)") (justify Left) (extent 10.17587 mm 135.0) )
    (line (pt 10295.0 2317.5) (pt 10495.0 2317.5) )(line (pt 10295.0 4067.5) (pt 10495.0 4067.5) )(line (pt 895.0 4067.5) (pt 1095.0 4067.5) )(text (pt 10395.0 3192.5) "3" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 4942.5) "2" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 6717.5) "1" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 10395.0 1417.5) "4" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 1417.5) "4" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 3192.5) "3" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 4942.5) "2" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 995.0 6717.5) "1" (textStyleRef "T:H180W10") (justify Center) (extent 145.0 235.0) )
    (text (pt 2095.0 7517.5) "A" (textStyleRef "T:H180W10") (justify Center) (extent 3.39725 mm 235.0) )
    (text (pt 4520.0 7517.5) "B" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 6895.0 7517.5) "C" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 9295.0 7517.5) "D" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 9295.0 617.5) "D" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 6895.0 617.5) "C" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 4495.0 617.5) "B" (textStyleRef "T:H180W10") (justify Center) (extent 3.82587 mm 235.0) )
    (text (pt 2095.0 617.5) "A" (textStyleRef "T:H180W10") (justify Center) (extent 3.39725 mm 235.0) )
  )
  (sheet "MAIN" (sheetNum 2)
    (fieldSetRef "(Default)")
    (text (pt 7700.0 1500.0) "ASAP probe breakout" (textStyleRef "(DefaultTTF)") (extent 27.84738 mm 3.7703 mm) )
    (field "Author" (pt 9772.0 884.0) (textStyleRef "(DefaultTTF)") )
    (field "Revision" (pt 9948.0 1107.0) (textStyleRef "(DefaultTTF)") )
    (field "Modified Date" (pt 7763.0 882.0) (textStyleRef "(DefaultTTF)") )
    (field "Filename" (pt 7939.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Sheet Number" (pt 9610.0 733.0) (textStyleRef "(DefaultTTF)") )
    (field "Number Of Sheets" (pt 10053.0 731.0) (textStyleRef "(DefaultTTF)") )
    (drawBorder True)
    (EntireDesign True)
    (isRotated True)
    (pageSize Size_A)
    (scaleFactor  1.00)
    (offset 0.0 0.0)
    (PrintRegion 
      (pt 1495.0 719.3) (pt 10188.8 7290.4) )
  )
  (schematicPrintSettings 
    (sheetList 
      (sheetRef 1)
    )
  )

  (programState 
    (gridState 
      (currentAbsGrid "100.0mil")
      (currentRelGrid "100.0mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording True))
    (currentTextStyle "(DefaultTTF)")
  )

  (reportSettings 
    (reportStyle reportStyleAccel)
    (reportDestination DestinationScreen)
    (pt 0.0 0.0) 
    (reportDefinitions 
      (reportDefinition 
        (reportName "Attributes")
        (reportExtension "atr")
        (reportType ReportTypeAttributes)
        (reportLinesPerPage 70)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "OriginalName")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "Description")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "ComponentField7")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField6")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField1")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField2")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField3")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField4")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField5")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
          )
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Bill of Materials")
        (reportExtension "bom")
        (reportShowFlag True)
        (reportType ReportTypeBillOfMaterials)
        (reportLinesPerPage 62)
        (reportColumnWidth 25)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 3)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "_Count")
              (reportFieldType PropertyTypeCount)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "ComponentName")
              (reportFieldType PropertyTypeComponentName)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 13)
            )
            (reportField 
              (reportFieldName "PatternName")
              (reportFieldType PropertyTypePatternName)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
            (reportField 
              (reportFieldName "OriginalName")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "Description")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "ComponentField6")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField7")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "SimType")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimModel")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "SimFile")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimPins")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SimNetlist")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 10)
            )
            (reportField 
              (reportFieldName "OrigRefDes")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldColumnWidth 10)
            )
            (reportField 
              (reportFieldName "Part Number")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 11)
            )
            (reportField 
              (reportFieldName "ComponentField1")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField2")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField3")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField4")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
            (reportField 
              (reportFieldName "ComponentField5")
              (reportFieldType PropertyTypeAttribute)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 15)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Global Nets")
        (reportExtension "gnr")
        (reportType ReportTypeGlobalNets)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "NetName")
              (reportFieldType PropertyTypeNetname)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 7)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Last Used RefDes")
        (reportExtension "lud")
        (reportType ReportTypeLastRefdes)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Value")
              (reportFieldType PropertyTypeCompValue)
              (reportFieldSortOrder 2)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 5)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Library Contents")
        (reportExtension "lct")
        (reportType ReportTypeLibrary)
        (reportLinesPerPage 62)
        (reportColumnWidth 15)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
      )
      (reportDefinition 
        (reportName "Parts Locations")
        (reportExtension "plc")
        (reportType ReportTypePartsLocations)
        (reportLinesPerPage 62)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "SheetNum")
              (reportFieldType PropertyTypeSheetnumber)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
            (reportField 
              (reportFieldName "LocationX")
              (reportFieldType PropertyTypeLocationX)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "LocationY")
              (reportFieldType PropertyTypeLocationY)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 9)
            )
            (reportField 
              (reportFieldName "Rotation")
              (reportFieldType PropertyTypeRotation)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 8)
            )
          )
        )
      )
      (reportDefinition 
        (reportName "Parts Usage")
        (reportExtension "ptu")
        (reportType ReportTypePartsUsage)
        (reportLinesPerPage 62)
        (reportColumnWidth 20)
        (reportHeader "")
        (reportFooter "")
        (reportShowCDFPreface True)
        (reportShowColumnNames True)
        (reportFieldsSections 
          (reportFields 
            (reportField 
              (reportFieldName "RefDes")
              (reportFieldType PropertyTypeRefdes)
              (reportFieldSortOrder 1)
              (reportFieldSortType ascending)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 6)
            )
            (reportField 
              (reportFieldName "Type")
              (reportFieldType PropertyTypeType)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 4)
            )
            (reportField 
              (reportFieldName "Unused Parts")
              (reportFieldType PropertyTypeUnusedParts)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 12)
            )
            (reportField 
              (reportFieldName "ComponentLibrary")
              (reportFieldType PropertyTypeComponentLibrary)
              (reportFieldSortOrder 0)
              (reportFieldSortType None)
              (reportFieldShowFlag True)
              (reportFieldColumnWidth 16)
            )
          )
        )
      )
    )
  )
)
