#!/bin/sh
tmpdir=/tmp/$2
rm -r $tmpdir
mkdir $tmpdir
echo "Job name: " $2 >$tmpdir/READ.ME
cat >>$tmpdir/read.me <<EOF
TOP 0.5 ounce copper
BRD Flex board outline
COV 1 mil polyimide coverlay
TSS Top silkscreen
FAB Fabrication drawing


Rob MacLachlan
email: ram@ri.cmu.edu
phone: 412-445-8113
EOF

for foo in TOP BRD COV FAB TSS;
do
  cp -p $1.$foo $tmpdir/$2.$foo
done

cd $tmpdir
rm -f $2.ZIP
zip $2.ZIP *
